@Library('my_ocp_sharelib') _  
import com.aviro.OpenShiftHelper  

pipeline {
    //agent any  
    agent {
        label 'builder'
    }

    environment {
        OC_TOKEN = credentials('openshift-id')  // Jenkins credentials
        OC_SERVER = "https://api.rm3.7wse.p1.openshiftapps.com:6443"
        PROJECT = "moussacloudwade-dev"
        IMAGE = "dockermoisa/challengewebapp:latest"
        APP_NAME = "labisi2025"
        APP_DEPLOYMENT = "labisi2025-00001-deployment"
    }

    stages {
        stage('Login to OpenShift') {
            steps {
                script {
                    OpenShiftHelper.login(this, OC_TOKEN, OC_SERVER)
                }
            }
        }

        // stage('Deploy Application') {
        //     steps {
        //         script {
        //             OpenShiftHelper.deploy(this, PROJECT, IMAGE, APP_NAME)
        //         }
        //     }
        // }

        stage('Deploy Application') {
            steps {
                script {
                   //OpenShiftHelper.deploy(this, PROJECT, IMAGE, APP_NAME)
                   sh "oc project ${project}"
                   //sh "oc delete app ${APP_DEPLOYMENT}"
                   sh "oc new-app ${IMAGE} -name=${APP_NAME} --namespace=${PROJECT}"
                }
            }
        }

        stage('Check Deployment Status') {
            steps {
                script {
                    if (!OpenShiftHelper.checkDeployment(this, PROJECT, APP_NAME, APP_DEPLOYMENT)) {
                        error "Le déploiement a échoué !"
                    } else {
                        echo "L'application a été déployée avec succès sur OpenShift !"
                    }
                }
            }
        }
    }
}
