@Library('my_ocp_sharelib') _  
import com.aviro.OpenShiftHelper  

pipeline {
    agent any  

    environment {
        OC_TOKEN = credentials('openshift-id')  // Jenkins credentials
        OC_SERVER = "https://api.rm3.7wse.p1.openshiftapps.com:6443"
        PROJECT = "moussacloudwade-dev"
        IMAGE = "dockermoisa/labisi2025:latest"
        APP_NAME = "labisi2025"
    }

    stages {
        stage('Login to OpenShift') {
            steps {
                script {
                    OpenShiftHelper.login(this, OC_TOKEN, OC_SERVER)
                }
            }
        }

        stage('Deploy Application') {
            steps {
                script {
                    OpenShiftHelper.deploy(this, PROJECT, IMAGE, APP_NAME)
                }
            }
        }

        stage('Check Deployment Status') {
            steps {
                script {
                    if (!OpenShiftHelper.checkDeployment(this, PROJECT, APP_NAME)) {
                        error "❌ Le déploiement a échoué !"
                    } else {
                        echo "✅ L'application a été déployée avec succès sur OpenShift !"
                    }
                }
            }
        }
    }
}
